name: "IPFS Daemon"
description: "Add-on to run IPFS Daemon"
version: "1.3.1"
slug: "ipfs-daemon"
init: false
startup: services
host_network: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
